name: Dev Branch
on:
  push:
    branches:
      - 'dev'

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v2
        with:
            arguments: build
      - uses: gradle/gradle-build-action@v2
        with:
            arguments: test